namespace FaceitLib.Constants
{
    public static class Countries
    {
        public static string Andorra { get { return "AD"; } }
        public static string UnitedArabEmirates { get { return "AE"; } }
        public static string Afghanistan { get { return "AF"; } }
        public static string AntiguaandBarbuda { get { return "AG"; } }
        public static string Anguilla { get { return "AI"; } }
        public static string Albania { get { return "AL"; } }
        public static string Armenia { get { return "AM"; } }
        public static string Angola { get { return "AO"; } }
        public static string Antarctica { get { return "AQ"; } }
        public static string Argentina { get { return "AR"; } }
        public static string AmericanSamoa { get { return "AS"; } }
        public static string Austria { get { return "AT"; } }
        public static string Australia { get { return "AU"; } }
        public static string Aruba { get { return "AW"; } }
        public static string ÅlandIslands { get { return "AX"; } }
        public static string Azerbaijan { get { return "AZ"; } }
        public static string BosniaandHerzegovina { get { return "BA"; } }
        public static string Barbados { get { return "BB"; } }
        public static string Bangladesh { get { return "BD"; } }
        public static string Belgium { get { return "BE"; } }
        public static string BurkinaFaso { get { return "BF"; } }
        public static string Bulgaria { get { return "BG"; } }
        public static string Bahrain { get { return "BH"; } }
        public static string Burundi { get { return "BI"; } }
        public static string Benin { get { return "BJ"; } }
        public static string SaintBarthelemy { get { return "BL"; } }
        public static string Bermuda { get { return "BM"; } }
        public static string BruneiDarussalam { get { return "BN"; } }
        public static string Bolivia { get { return "BO"; } }
        public static string Brazil { get { return "BR"; } }
        public static string Bahamas { get { return "BS"; } }
        public static string Bhutan { get { return "BT"; } }
        public static string BouvetIsland { get { return "BV"; } }
        public static string Botswana { get { return "BW"; } }
        public static string Belarus { get { return "BY"; } }
        public static string Belize { get { return "BZ"; } }
        public static string Canada { get { return "CA"; } }
        public static string CocosIslands { get { return "CC"; } }
        public static string DemocraticRepublicOfTheCongo { get { return "CD"; } }
        public static string CentralAfricanRepublic { get { return "CF"; } }
        public static string Congo { get { return "CG"; } }
        public static string Switzerland { get { return "CH"; } }
        public static string CotedIvoire { get { return "CI"; } }
        public static string CookIslands { get { return "CK"; } }
        public static string Chile { get { return "CL"; } }
        public static string Cameroon { get { return "CM"; } }
        public static string China { get { return "CN"; } }
        public static string Colombia { get { return "CO"; } }
        public static string CostaRica { get { return "CR"; } }
        public static string Cuba { get { return "CU"; } }
        public static string CaboVerde { get { return "CV"; } }
        public static string Curaçao { get { return "CW"; } }
        public static string ChristmasIsland { get { return "CX"; } }
        public static string Cyprus { get { return "CY"; } }
        public static string CzechRepublic { get { return "CZ"; } }
        public static string Germany { get { return "DE"; } }
        public static string Djibouti { get { return "DJ"; } }
        public static string Denmark { get { return "DK"; } }
        public static string Dominica { get { return "DM"; } }
        public static string DominicanRepublic { get { return "DO"; } }
        public static string Algeria { get { return "DZ"; } }
        public static string Ecuador { get { return "EC"; } }
        public static string Estonia { get { return "EE"; } }
        public static string Egypt { get { return "EG"; } }
        public static string WesternSahara { get { return "EH"; } }
        public static string Eritrea { get { return "ER"; } }
        public static string Spain { get { return "ES"; } }
        public static string Ethiopia { get { return "ET"; } }
        public static string Finland { get { return "FI"; } }
        public static string Fiji { get { return "FJ"; } }
        public static string FalklandIslands { get { return "FK"; } }
        public static string Micronesia { get { return "FM"; } }
        public static string FaroeIslands { get { return "FO"; } }
        public static string France { get { return "FR"; } }
        public static string Gabon { get { return "GA"; } }
        public static string UnitedKingdom { get { return "GB"; } }
        public static string Grenada { get { return "GD"; } }
        public static string Georgia { get { return "GE"; } }
        public static string FrenchGuiana { get { return "GF"; } }
        public static string Guernsey { get { return "GG"; } }
        public static string Ghana { get { return "GH"; } }
        public static string Gibraltar { get { return "GI"; } }
        public static string Greenland { get { return "GL"; } }
        public static string Gambia { get { return "GM"; } }
        public static string Guinea { get { return "GN"; } }
        public static string Guadeloupe { get { return "GP"; } }
        public static string EquatorialGuinea { get { return "GQ"; } }
        public static string Greece { get { return "GR"; } }
        public static string SouthGeorgiaandtheSouthSandwichIslands { get { return "GS"; } }
        public static string Guatemala { get { return "GT"; } }
        public static string Guam { get { return "GU"; } }
        public static string GuineaBissau { get { return "GW"; } }
        public static string Guyana { get { return "GY"; } }
        public static string HongKong { get { return "HK"; } }
        public static string HeardIslandandMcDonaldIslands { get { return "HM"; } }
        public static string Honduras { get { return "HN"; } }
        public static string Croatia { get { return "HR"; } }
        public static string Haiti { get { return "HT"; } }
        public static string Hungary { get { return "HU"; } }
        public static string Indonesia { get { return "ID"; } }
        public static string Ireland { get { return "IE"; } }
        public static string Israel { get { return "IL"; } }
        public static string IsleofMan { get { return "IM"; } }
        public static string India { get { return "IN"; } }
        public static string BritishIndianOceanTerritory { get { return "IO"; } }
        public static string Iraq { get { return "IQ"; } }
        public static string Iran { get { return "IR"; } }
        public static string Iceland { get { return "IS"; } }
        public static string Italy { get { return "IT"; } }
        public static string Jersey { get { return "JE"; } }
        public static string Jamaica { get { return "JM"; } }
        public static string Jordan { get { return "JO"; } }
        public static string Japan { get { return "JP"; } }
        public static string Kenya { get { return "KE"; } }
        public static string Kyrgyzstan { get { return "KG"; } }
        public static string Cambodia { get { return "KH"; } }
        public static string Kiribati { get { return "KI"; } }
        public static string Comoros { get { return "KM"; } }
        public static string SaintKittsandNevis { get { return "KN"; } }
        public static string SouthKorea { get { return "KR"; } }
        public static string Kuwait { get { return "KW"; } }
        public static string CaymanIslands { get { return "KY"; } }
        public static string Kazakhstan { get { return "KZ"; } }
        public static string Laos { get { return "LA"; } }
        public static string Lebanon { get { return "LB"; } }
        public static string SaintLucia { get { return "LC"; } }
        public static string Liechtenstein { get { return "LI"; } }
        public static string SriLanka { get { return "LK"; } }
        public static string Liberia { get { return "LR"; } }
        public static string Lesotho { get { return "LS"; } }
        public static string Lithuania { get { return "LT"; } }
        public static string Luxembourg { get { return "LU"; } }
        public static string Latvia { get { return "LV"; } }
        public static string Libya { get { return "LY"; } }
        public static string Morocco { get { return "MA"; } }
        public static string Monaco { get { return "MC"; } }
        public static string Moldova { get { return "MD"; } }
        public static string Montenegro { get { return "ME"; } }
        public static string SaintMartin { get { return "MF"; } }
        public static string Madagascar { get { return "MG"; } }
        public static string MarshallIslands { get { return "MH"; } }
        public static string Macedonia { get { return "MK"; } }
        public static string Mali { get { return "ML"; } }
        public static string Myanmar { get { return "MM"; } }
        public static string Mongolia { get { return "MN"; } }
        public static string Macao { get { return "MO"; } }
        public static string NorthernMarianaIslands { get { return "MP"; } }
        public static string Martinique { get { return "MQ"; } }
        public static string Mauritania { get { return "MR"; } }
        public static string Montserrat { get { return "MS"; } }
        public static string Malta { get { return "MT"; } }
        public static string Mauritius { get { return "MU"; } }
        public static string Maldives { get { return "MV"; } }
        public static string Malawi { get { return "MW"; } }
        public static string Mexico { get { return "MX"; } }
        public static string Malaysia { get { return "MY"; } }
        public static string Mozambique { get { return "MZ"; } }
        public static string Namibia { get { return "NA"; } }
        public static string NewCaledonia { get { return "NC"; } }
        public static string Niger { get { return "NE"; } }
        public static string NorfolkIsland { get { return "NF"; } }
        public static string Nigeria { get { return "NG"; } }
        public static string Nicaragua { get { return "NI"; } }
        public static string Netherlands { get { return "NL"; } }
        public static string Norway { get { return "NO"; } }
        public static string Nepal { get { return "NP"; } }
        public static string Nauru { get { return "NR"; } }
        public static string Niue { get { return "NU"; } }
        public static string NewZealand { get { return "NZ"; } }
        public static string Oman { get { return "OM"; } }
        public static string Panama { get { return "PA"; } }
        public static string Peru { get { return "PE"; } }
        public static string FrenchPolynesia { get { return "PF"; } }
        public static string PapuaNewGuinea { get { return "PG"; } }
        public static string Philippines { get { return "PH"; } }
        public static string Pakistan { get { return "PK"; } }
        public static string Poland { get { return "PL"; } }
        public static string SaintPierreandMiquelon { get { return "PM"; } }
        public static string Pitcairn { get { return "PN"; } }
        public static string PuertoRico { get { return "PR"; } }
        public static string Palestine { get { return "PS"; } }
        public static string Portugal { get { return "PT"; } }
        public static string Palau { get { return "PW"; } }
        public static string Paraguay { get { return "PY"; } }
        public static string Qatar { get { return "QA"; } }
        public static string Reunion { get { return "RE"; } }
        public static string Romania { get { return "RO"; } }
        public static string Serbia { get { return "RS"; } }
        public static string RussianFederation { get { return "RU"; } }
        public static string Rwanda { get { return "RW"; } }
        public static string SaudiArabia { get { return "SA"; } }
        public static string SolomonIslands { get { return "SB"; } }
        public static string Seychelles { get { return "SC"; } }
        public static string Sudan { get { return "SD"; } }
        public static string Sweden { get { return "SE"; } }
        public static string Singapore { get { return "SG"; } }
        public static string Slovenia { get { return "SI"; } }
        public static string SvalbardandJanMayen { get { return "SJ"; } }
        public static string Slovakia { get { return "SK"; } }
        public static string SierraLeone { get { return "SL"; } }
        public static string SanMarino { get { return "SM"; } }
        public static string Senegal { get { return "SN"; } }
        public static string Somalia { get { return "SO"; } }
        public static string Suriname { get { return "SR"; } }
        public static string SouthSudan { get { return "SS"; } }
        public static string SaoTomeandPrincipe { get { return "ST"; } }
        public static string ElSalvador { get { return "SV"; } }
        public static string SintMaarten { get { return "SX"; } }
        public static string SyrianArabRepublic { get { return "SY"; } }
        public static string Swaziland { get { return "SZ"; } }
        public static string TurksandCaicosIslands { get { return "TC"; } }
        public static string Chad { get { return "TD"; } }
        public static string FrenchSouthernTerritories { get { return "TF"; } }
        public static string Togo { get { return "TG"; } }
        public static string Thailand { get { return "TH"; } }
        public static string Tajikistan { get { return "TJ"; } }
        public static string Tokelau { get { return "TK"; } }
        public static string TimorLeste { get { return "TL"; } }
        public static string Turkmenistan { get { return "TM"; } }
        public static string Tunisia { get { return "TN"; } }
        public static string Tonga { get { return "TO"; } }
        public static string Turkey { get { return "TR"; } }
        public static string TrinidadandTobago { get { return "TT"; } }
        public static string Tuvalu { get { return "TV"; } }
        public static string Taiwan { get { return "TW"; } }
        public static string Tanzania { get { return "TZ"; } }
        public static string Ukraine { get { return "UA"; } }
        public static string Uganda { get { return "UG"; } }
        public static string UnitedStatesMinorOutlyingIslands { get { return "UM"; } }
        public static string UnitedStates { get { return "US"; } }
        public static string Uruguay { get { return "UY"; } }
        public static string Uzbekistan { get { return "UZ"; } }
        public static string HolySee { get { return "VA"; } }
        public static string SaintVincentandtheGrenadines { get { return "VC"; } }
        public static string Venezuela { get { return "VE"; } }
        public static string BritishVirginIslands { get { return "VG"; } }
        public static string USVirginIslands { get { return "VI"; } }
        public static string VietNam { get { return "VN"; } }
        public static string Vanuatu { get { return "VU"; } }
        public static string WallisandFutuna { get { return "WF"; } }
        public static string Samoa { get { return "WS"; } }
        public static string Yemen { get { return "YE"; } }
        public static string Mayotte { get { return "YT"; } }
        public static string SouthAfrica { get { return "ZA"; } }
        public static string Zambia { get { return "ZM"; } }
        public static string Zimbabwe { get { return "ZW"; } }
    }
}
